version: '3.8'

services:
  frontend:
    container_name: todo-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: todo-cloud-project-frontend:latest
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - todo-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    container_name: todo-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: todo-cloud-project-backend:latest
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
    networks:
      - todo-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/todos"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  todo-network:
    name: todo-network
    driver: bridge
   
